kind: pipeline
name: test

concurrency:
  limit: 2

steps:
- name: flake8
  image: alpine/flake8:3.7.9
  commands:
  - flake8

- name: leaks
  image: zricethezav/gitleaks:v6.2.0
  depends_on:
  - flake8

- name: 1-hoover
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.4.2
  commands:
  - export PROVISION=./tests/1-hoover
  - export VMCK_MEMORY=11500
  - export VMCK_CPUS=3
  - ./ci/run-vagrant-test.sh

- name: 2-hypothesis
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.4.2
  commands:
  - export VMCK_MEMORY=5000
  - export PROVISION=./tests/2-hypothesis
  - ./ci/run-vagrant-test.sh

- name: 3-codimd+dokuwiki
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.4.2
  commands:
  - export VMCK_MEMORY=3500
  - export PROVISION=./tests/3-codimd-dokuwiki
  - ./ci/run-vagrant-test.sh

- name: 4-nextcloud+rocketchat
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.4.2
  commands:
  - export VMCK_MEMORY=5500
  - export PROVISION=./tests/4-nextcloud-rocketchat
  - ./ci/run-vagrant-test.sh

- name: 5-hoover+hypothesis+nextcloud
  depends_on:
  - flake8
  image: vmck/vagrant-vmck:0.4.2
  commands:
  - export VMCK_MEMORY=18500
  - export VMCK_CPUS=3
  - export PROVISION=./tests/5-hoover-hypothesis-nextcloud
  - ./ci/run-vagrant-test.sh
